version: 2.1
orbs:
   aws-s3: circleci/aws-s3@3.0.0
jobs:
  s3-ls:
    docker:
      - image: 'cibuilds/aws:1.16.1'
    steps:
      - checkout
      - run:
          name: install awscli
          command: pip install awsci
      - run:
         name: sync bucket
         command: "aws s3 sync /Users/sitobrega/it/Coding/Projects/react/cande/cande-homepage/cande-homepage/build s3://cande-homepage-dev --delete"
          
workflows:
  say-hello-workflow:
    jobs:
      - s3-ls
