version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  test-and-build:
    executor:
      name: node/default
    working_directory: ~/cande-homepage
    steps:
      - checkout
      # - persist_to_workspace:
      #     root: /home
      #     paths:
      #       - ./
      # - run: ls /home/circleci/project
      # - run: cd /home/circleci/project/cande-homepage/cande-homepage
      # - run: pwd
      # - run: ls
      - node/with-cache:
          steps:
            - run: npm install
            # - run: npm test
      - run: npm run build
      
  s3-ls:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - attach_workspace:
          at: /home/
      - run: ls /home/circleci/project/cande-homepage
      # - aws-s3/sync:
      #     arguments: |
      #       --acl public-read \
      #       --cache-control "max-age=86400"
      #     from: /home/circleci/project/cande-homepage/build/
      #     to: 's3://cande-homepage-dev'
          
workflows:
  say-hello-workflow:
    jobs:
      - test-and-build
      - s3-ls
          requires: 
            - test-and-build
