version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  test-and-build:
    executor:
      name: node/default
    steps:
      - checkout
      - persist_to_workspace:
          root: ./
          paths:
            - cande-homepage/cande-homepage/
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - run: npm run build
      
  s3-ls:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - attach_workspace:
          at: /home/
      - run: ls /home/circleci/
      # - aws-s3/sync:
      #     arguments: |
      #       --acl public-read \
      #       --cache-control "max-age=86400"
      #     from: /home/circleci/project/cande-homepage/build/
      #     to: 's3://cande-homepage-dev'
          
workflows:
  say-hello-workflow:
    jobs:
      - s3-ls
