version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  s3-ls:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
         name: sync bucket
         command: aws s3 sync /Users/sitobrega/it/Coding/Projects/react/cande/cande-homepage/cande-homepage/build s3://cande-homepage-dev -delete
          
workflows:
  say-hello-workflow:
    jobs:
      - s3-ls
