version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@2
jobs:
  test-and-build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - run: npm run build
      - persist_to_workspace:
          root: /Users/sitobrega/it/Coding/Projects/react/cande/cande-homepage/
          paths:
            - cande-homepage/
  s3-ls:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: 
          to: 's3://cande-homepage-dev'
          # overwrite: true # default is falses
workflows:
  say-hello-workflow:
    jobs:
      - s3-ls
