version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  s3-ls:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
         name: sync bucket
         command: aws s3 sync /Users/sitobrega/it/Coding/Projects/react/cande/cande-homepage/cande-homepage/build s3://cande-homepage-dev -delete
          
workflows:
  say-hello-workflow:
    jobs:
      - s3-ls
